apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podgroups.batch.scheduler.tencent.com
spec:
  group: batch.scheduler.tencent.com
  names:
    kind: PodGroup
    plural: podgroups
    singular: podgroup
    shortNames:
      - pg
      - pgs
  scope: Namespaced
  version: v1